# Copyright (c) 2016-2019 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Aige  Docs
site_description: 苍成坤的 blog
site_author: Aige
#配置站点的域名
site_url: https://squidfunk.github.io/mkdocs-material/

# Repository  配置头部显示的数据
repo_name: Aige github
repo_url: https://github.com/cangchengkun/Docs
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2016 - 2019  Aige'

# Configuration
theme:
  name: null
  custom_dir: material
  # custom_dir: 'mkdocs-material/material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Customization
extra:
  social:
    - type: globe
      link: http://struct.cc
    - type: github-alt
      link: https://github.com/cangchengkun/Docs
    - type: twitter
      link: https://twitter.com/Aige25868905
    - type: facebook
      link: https://www.facebook.com/cangck.danmo
    - type: youtube
      link: https://www.youtube.com/
  search:
    language: 'jp'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Page tree
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Project:
    - SkyRoad:
      - WebSocket: project/websocket.md
  - Android:
    - Flutter:
      - Flutter学习路线: android/flutterdev/flutteradvance.md
      - FlutterUI和Engine关联: android/flutter/flutterUIframework.md
      - FlutterUI框架绘制过程: android/flutterdev/FlutterWidgetinit.md
      - PlatformChannel: android/flutterdev/platform_channels.md
      - ISOlate使用: android/flutterdev/isolatedev.md
      - Future&Stream: android/flutterdev/futterStream.md
      - Flutter生命周期管理: android/flutterdev/applifecyclestate.md
      - FlutterNavigator: android/flutterdev/flutterNavigator.md
      - Flutter库: android/flutter/FlutterLib.md
      - 代码片段: android/flutterdev/fluttersnip.md
      - FlutterKey: android/flutter/FlutterKey.md
      - Flutter: android/flutter/flutter.md
      - FlutterSdk: android/flutter/FlutterTools.md
      - Flutter项目经验: android/flutter_project/flutterApp.md
      - 自定义Widget: android/flutterdev/customWidget.md
      - Flutter图片加载: android/flutterdev/flutterImageProvider.md
      - FlutterAndroid&IOS打包: android/flutterdev/Flutterdeployment.md
      - Flutter测试: android/flutterdev/flutterTest.md
      - Architecture: android/flutter/Architecture.md
      - Flutter开发: android/flutter/flutterDev.md
      - example: android/flutter/flutterexample.md
      - Flutter常见问题: android/flutter/FlutterQuestion.md
      - FlutterUI: android/flutter/flutterUI.md
      - 面试资料: android/flutter/interview.md
    - FlutterEngine:
      - Engine源代码下载: android/flutter/downEngine.md
      - 编译模式: android/flutter/ComplieMode.md
      - FlutterEngine编译: android/flutter/EngineCompile.md
      - GNTools: android/flutter/GNTools.md
      - Ninja编译系统 : android/flutter/NinjaSystem.md
      - Engine编译构建: android/flutter/EngineCompile.md
      - Engine编译产物: android/flutter/FlutterComplieFile.md
      - 编译模式: android/flutter/ComplieMode.md
      - Apk&ipd包分析: android/flutter/apkfile.md
      - Android加载Dart文件: android/flutter/flutterAndroidInit.md
      - Android初始化View: android/flutter/AndroidViewinit.md
      - Engine初始化: android/flutter/EngineInit.md
      - EngineView初始化: android/flutter/EngineView.md
      - C++智能指针: android/flutter/SmartPtr.md
      - NativeExtensions: android/flutter/NativeExtensions.md
      - MessageLoop: android/flutter/MessageLoop.md
      - 初始化DartVM: android/flutter/DartVM.md
      - PlatformChannel: android/flutter/platformplugin.md
      - DartVMServiceProtocol: android/flutter/DartVMServiceProtocol.md
      - FlutterSupportView: android/flutter/FlutterSupportView.md
      - 性能优化: android/flutter/profile.md
      - reviewCode: android/flutter/reviewCode.md
      - 资料: android/flutter/DevResource.md
      - FlutterUI通信Android&IOS: android/flutter/fluttercommunicationAndroidorIOS.md
      - FlutterEngine源码编译: android/flutter/flutterEngine.md
      - Flutter引擎目录: android/flutter/flutterenginedir.md


    - ReactNative:
      - ReactNative: android/rn/react_native.md
    - Awsamplify:
      - Awsamplify: android/aws-android/awsamplify.md
    - AndroidTools: android/androidTools.md
    - Issue常见问题: android/issue/Androidissue.md

  - Python:
    - 基础:
      - 语言基础: python/base/pythonlang.md
      - 高级开发: python/base/advancesPython.md
      - Python反射: python/base/pythoninspect.md
      - 开发环境:
        - 环境: python/base/pythonEnv.md
    - 爬虫:
      - 爬虫基础: python/scrapy/scrapyBase.md
      - 爬虫库: python/scrapy/scrapylib.md
      - 爬虫实战: python/scrapy/spiderdemo.md
    - 服务器开发:
      - WEB:
        - 主流服务器介绍: python/server/pythonweb.md
        - 服务器常用软件: python/server/serverbase.md
        - Oauth2服务器搭建: python/server/pythonOauth.md
      - aws:
        - AWSpython使用: python/server/aws/pyaws.md
        - 无服务: python/server/aws/serverless.md
      - Django开发:
        - Dajngo信号机制: python/server/django/djangosignals.md
        - 日志配置: python/server/django/djangoLogger.md
        - Djangomessage: python/server/django/djangosignals.md
        - JsonEncoder: python/server/django/JSONEncoder.md
        - 中间件: python/server/django/middleware.md
        - 常见问题: python/server/django/question.md
      - 部署:
        - zappa: python/server/zappa.md

    - 开发工具: python/pythonTools.md


  - IoT:
    - Alexa: iot/Alexa.md
    - AWSIOT: iot/awsiot.md
    - IotCore: iot/iotCore.md
    - program: iot/program.md
    - protocol: iot/protocol.md
    - UserManager: iot/usermanager.md
    - aws开发工具: iot/developerTools.md

  - Secret:
    - 安全: secret/reousrce.md
    - 端口扫描工具: tools/networktools.md

  - Linux:
    - 资料: linux/resource.md

  - Shell:
    - Shell: shell/shellresource.md

  - Tools:
    - AndroidStudio: extensions/admonition.md
    - Atom: tools/atom.md
    - Vim: tools/vim.md
    - Chrome: extensions/metadata.md
    - Markdown: tools/markdown.md
    - Material for MkDocs: tools/material.md
    - Git: tools/git.md
    - VSCode: tools/VSCode.md
    - 数据分析: tools/datareporting.md

  - Download:
    - download: download/download.md
  # - Customization: customization.md
  # - Compliance with GDPR: compliance.md
  # - Release notes: release-notes.md
  # - Author's notes: authors-notes.md
  # - Contributing: contributing.md
  # - License: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
