# Copyright (c) 2016-2019 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Aige  Docs
site_description: 苍成坤的 blog
site_author: Aige
#配置站点的域名
site_url: https://squidfunk.github.io/mkdocs-material/

# Repository  配置头部显示的数据
repo_name: Aige github
repo_url: https://github.com/cangchengkun/Docs
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2016 - 2019  Aige'

# Configuration
theme:
  name: null
  custom_dir: material
  # custom_dir: 'mkdocs-material/material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Customization
extra:
  social:
    - type: globe
      link: http://struct.cc
    - type: github-alt
      link: https://github.com/cangchengkun/Docs
    - type: twitter
      link: https://twitter.com/Aige25868905
    - type: facebook
      link: https://www.facebook.com/cangck.danmo
    - type: youtube
      link: https://www.youtube.com/
  search:
    language: 'jp'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Page tree
nav:
  - Home: index.md
  - Getting started: getting-started.md

  - Android:
    - Admonition: extensions/pymdown.md


  - Flutter:
    - Flutter: android/flutter.md
    - FlutterSdk: android/FlutterTools.md
    - 编译模式: android/ComplieMode.md
    - FlutterEngine编译: android/EngineCompile.md
    - GNTools: android/GNTools.md
    - Ninja编译系统 : android/NinjaSystem.md
    - Flutter编译产物: android/FlutterComplieFile.md
    - Android加载Dart文件: android/flutterAndroidInit.md
    - Android初始化View: android/AndroidViewinit.md
    - Engine初始化: android/EngineInit.md
    - EngineView初始化: android/EngineView.md
    - C++智能指针: android/SmartPtr.md
    - NativeExtensions: android/NativeExtensions.md
    - MessageLoop: android/MessageLoop.md
    - 初始化DartVM: android/DartVM.md
    - PlatformChannel: android/platformplugin.md
    - example: android/flutterexample.md
    - runApp: android/runApp.md
    - DartVMServiceProtocol: android/DartVMServiceProtocol.md
    - FlutterSupportView: android/FlutterSupportView.md
    - 性能优化: android/profile.md
    - Architecture: android/Architecture.md
    - reviewCode: android/reviewCode.md
    - 资料: android/DevResource.md

  - Python:
    - spider: python/scrapylib.md
    - scrapydemo: python/spiderdemo.md
    - awsPython操作: python/pyaws.md
    - PythonTools: python/pythonTools.md
    - Python基础: python/BasePython.md
    - Django:
      - Django: python/django/django.md
      - Signals: python/django/djangosignals.md
      - Messages: python/django/djangomessage.md
      - JSONEncoder: python/django/JSONEncoder.md
      - Django日志配置: python/django/djangoLogger.md
    - 资料: python/resource.md

  - IoT:
    - Alexa: iot/Alexa.md
    - AWSIOT: iot/awsiot.md
    - IotCore: iot/iotCore.md
    - program: iot/program.md
    - protocol: iot/protocol.md
    - UserManager: iot/usermanager.md

  - Secret:
    - 安全: secret/reousrce.md

  - Linux:
    - 资料: linux/resource.md

  - Shell:
    - Shell: shell/shellresource.md

  - Tools:
    - AndroidStudio: extensions/admonition.md
    - Atom: tools/atom.md
    - Vim: tools/vim.md
    - Chrome: extensions/metadata.md
    - Markdown: tools/markdown.md
    - Material for MkDocs: tools/material.md
    - Git: tools/git.md
    - VSCode: tools/VSCode.md
    - 数据分析: tools/datareporting.md

  - Download:
    - download: download/download.md
  # - Customization: customization.md
  # - Compliance with GDPR: compliance.md
  # - Release notes: release-notes.md
  # - Author's notes: authors-notes.md
  # - Contributing: contributing.md
  # - License: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
